image: node:latest

stages:
  - Build
  - Test
  - Deploy
  - Deployement tests

build website:
  stage: Build
  script:
    - echo $CI_COMMIT_SHORT_SHA
    - npm install
    - npm install -g gatsby-cli
    - gatsby build
    - sed -i "s/%%VERSION%%/$CI_COMMIT_SHORT_SHA/" ./public/index.html
  artifacts:
    paths:
      - ./public


test artifact:
  image: alpine:latest
  stage: Test
  script:
    - grep -q "Gatsby" ./public/index.html

test website:
  stage: Test
  script:
    - npm install 
    - npm install -g gatsby-cli
    - gatsby serve &
    - sleep 3
    - curl "http://localhost:9000" | grep -q "Gatsby"
    - curl "http://localhost:9000" | grep -q $CI_COMMIT_SHORT_SHA

deploy to surge:
  stage: Deploy
  script:
    - npm install -g surge
    - surge --project ./public --domain dedsec3.surge.sh


test deployment:
  stage: Deployement tests
  script:
    - curl "http://dedsec3.surge.sh" | grep -q "Gatsby"    