stages:
  - build
  - test

build the website:
  stage: build
  image: node:latest
  script:
    - npm install
    - npm install -g gatsby-cli
    - gatsby build
  artifacts:
    paths:
      - ./public


test the artifact:
  image: alpine:latest
  stage: test
  script:
    - grep -q "Gatsby" ./public/index.html

test the website:
  image: node:latest
  stage: test
  script:
    - npm install 
    - npm install -g gatsby-cli
    - gatsby serve
    - curl  "http://localhost:9000" | grep -q "Gatsby"
