stages:
  - build
  - test

build the website:
  stage: build
  image: node:latest
  script:
    - npm install
    - npm install -g gatsby-cli
    - gatsby build
  artifacts:
    paths:
      - ./public


test the artifact:
  stage: test
  script:
    - grep "Gatsby" ./public/index.html