image: node:latest

stages:
  - build
  - test
  - deploy

build the website:
  stage: build
  script:
    - npm install
    - npm install -g gatsby-cli
    - gatsby build
  artifacts:
    paths:
      - ./public


test the artifact:
  image: alpine:latest
  stage: test
  script:
    - grep -q "Gatsby" ./public/index.html

test the website:
  stage: test
  script:
    - npm install 
    - npm install -g gatsby-cli
    - gatsby serve &
    - sleep 3
    - curl  "http://localhost:9000" | grep -q "Gatsby"

deploy to surge:
  stage: deploy
  script:
    - npm install -g surge
    - surge --project ./public --domain dedsec3.surge.sh